delete parent; make plugin versions upgradable in children repo; add java 14 and 15 support.
meterware/multirelease-parent pull request #4
Opened 2020-06-18 20:30 UTC by XenoAmess

2020-06-19 13:44 UTC, XenoAmess commented
@russgold any ideas?

2020-12-31 15:59 UTC, russgold commented
Whoops - just received notification of these changes. I'll take a look, thanks.

2020-12-31 16:10 UTC, russgold requested changes
The changes look good - but I cannot accept the PR with a change to the group name. Can you revert that in your PR?

2020-12-31 16:10 UTC, russgold commented on README.md
> +        <groupId>com.xenoamess</groupId>
Are you branching or looking to update the original?

2020-12-31 16:10 UTC, russgold commented on pom.xml
>                      <!-- enable java9 - java13 compilations -->
Should probably update this line

2020-12-31 16:14 UTC, XenoAmess commented
> The changes look good - but I cannot accept the PR with a change to the group name. Can you revert that in your PR?

I changed it only because I waited for your response for too long, and I need to use that,so I decide to change that,thus I can push it into maven central.
If you be agree to accept this pr I'm glad to rename it back, and rebase it.

2020-12-31 16:30 UTC, XenoAmess commented on pom.xml
>                      <!-- enable java9 - java13 compilations -->
@russgold done

2020-12-31 16:30 UTC, XenoAmess commented on README.md
> +        <groupId>com.xenoamess</groupId>
@russgold done

2020-12-31 16:31 UTC, XenoAmess commented
@russgold done. please do a review. thanks!

2020-12-31 16:37 UTC, russgold approved these changes

2020-12-31 16:38 UTC, merged